### ISSUE TITLE
Pre-trained embeddings links are inaccessible?

### ISSUE THREAD

**Issue by drussellmrichie** [agnusmaximus/Word2Bits#9]
I click on any of the links and get:

> Access forbidden!
[an error occurred while processing this directive] You don't have permission to access the requested directory. There is either no index document or the directory is read-protected.

**Comment by agnusmaximus** [comment]
Sorry about the late reply! I need to re-upload the word vectors to a new server. Will update this thread when its done.

**Comment by agnusmaximus** [comment]
The quantized word vectors have been uploaded to google drive and linked in the readme. The un-quantized vectors will require some more time to upload, will update this thread when those are also uploaded.

**Comment by drussellmrichie** [comment]
Thank you!

**Comment by Zhaoxiangyun** [comment]
> The quantized word vectors have been uploaded to google drive and linked in the readme. The un-quantized vectors will require some more time to upload, will update this thread when those are also uploaded.

Hi, have you finished the un-quantized vectors uploading? I am waiting to use it in my research project. Thank you.

**Comment by agnusmaximus** [comment]
Yes, the un-quantized vectors have been uploaded.
